import { Cormorant_Garamond, Inter, Plus_Jakarta_Sans, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Doc Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-foreground">
        <header className="z-20 shadow-sm fixed w-full bg-background">
          <Navbar />
        </header>
        <main className="pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
