import { Cormorant_Garamond, Inter, Plus_Jakarta_Sans, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
   display: 'swap',
});

export const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: 'swap',
});

export const metadata = {
  title: "Doc Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-foreground">
        <header className="shadow-sm fixed w-full bg-background">
          <Navbar />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
